### PR TITLE
Pass UIDs to python strategy code

### PR DESCRIPTION
**Pull request by egelja**
now we support C++ :)

### CODE REVIEW

**Comment by stevenewald** [comment]
How does this help support C++?

**Comment by egelja** [comment]
Just trust me bro

**Comment by stevenewald** [comment]
Are u gonna spawn in a cpp process from python??

**Comment by stevenewald** [comment]
I like the idea but if users are able to do that we haven't put enough guardrails on

**Comment by egelja** [comment]
#101

**Review by stevenewald — CHANGES_REQUESTED** [review]
I like the idea but ideally it isn't possible for users to spawn their own process and ESPECIALLY not possible for them to directly connect to RMQ

**Comment by stevenewald** [comment]
I'm confused, won't nsjail prevent them from connecting to RMQ?

**Pull request closed without merging**
