### PR TITLE
add submission support to new frontend

### PR DESCRIPTION
**Pull request by glasss13**

### CODE REVIEW

**Comment by glasss13** [comment]
looking at the diff im realizing there is a lot of re-formatting. You think we should add a prettier file to standardize?

**Comment by glasss13** [comment]
also do you want me to delete the old website directory?

**Comment by stevenewald** [comment]
Can we make it so resumes have to be uploaded before they can submit registration

**Review by stevenewald — APPROVED** [review]
LGTM great work

**Pull request merged**
