### PR TITLE
Yanglet liu patch 1

### PR DESCRIPTION
**Pull request by YangletLiu**

### CODE REVIEW

**Comment by egelja** [comment]
Wrong repo, please PR against main in https://github.com/FinRL-Contest/ACM_ICAIF_2023

**Comment by echavemann** [comment]
2 loc change

**Comment by echavemann** [comment]
i will make it against FinRl contest

**Comment by YangletLiu** [comment]
> i will make it against FinRl contest

Sorry, I did not notice the directory change of Github repo.
No intention of making this PR.  Thanks.

**Pull request closed without merging**
